packages:
  - packages/*
  - examples/*

catalog:
  '@ai-sdk/openai': ^1.3.22
  '@apidevtools/swagger-parser': ^10.1.1
  '@dexaai/dexter': ^4.1.1
  '@e2b/code-interpreter': ^1.5.1
  '@fisch0920/config': ^1.1.4
  '@googleapis/customsearch': ^4.0.1
  '@langchain/core': ^0.3.60
  '@langchain/openai': ^0.5.14
  '@llamaindex/openai': ^0.4.4
  '@llamaindex/workflow': ^1.1.9
  '@mastra/core': ^0.10.6
  '@modelcontextprotocol/sdk': ^1.13.0
  '@nangohq/node': 0.42.22
  '@types/jsrsasign': ^10.5.15
  '@types/node': ^24.0.4
  '@xsai/tool': ^0.3.0-beta.4
  ai: ^4.3.16
  bumpp: ^10.2.0
  camelcase: ^8.0.0
  cleye: ^1.3.4
  decamelize: ^6.0.0
  dedent: ^1.6.0
  del-cli: ^6.0.0
  delay: ^6.0.0
  dotenv: ^16.5.0
  duck-duck-scrape: ^2.2.7
  eslint: ^9.29.0
  execa: ^9.6.0
  exit-hook: ^4.0.0
  fast-xml-parser: ^5.2.5
  genkit: ^1.13.0
  genkitx-openai: ^0.22.3
  google-auth-library: ^9.15.1
  googleapis: ^150.0.1
  json-schema-to-zod: ^2.6.1
  jsonrepair: ^3.12.0
  jsrsasign: ^10.9.0
  ky: ^1.8.1
  langchain: ^0.3.29
  lint-staged: ^16.1.2
  llamaindex: ^0.11.8
  mathjs: ^13.2.3
  npm-run-all2: ^8.0.4
  octokit: ^5.0.3
  only-allow: ^1.2.1
  openai: ^5.5.1
  openai-fetch: ^3.4.2
  openai-zod-to-json-schema: ^1.0.3
  openapi-types: ^12.1.3
  p-map: ^7.0.3
  p-throttle: 6.2.0
  prettier: ^3.6.0
  restore-cursor: ^5.1.0
  simple-git-hooks: ^2.13.0
  string-strip-html: ^13.4.12
  syncpack: 14.0.0-alpha.10
  tsup: ^8.5.0
  tsx: ^4.20.3
  turbo: ^2.5.4
  twitter-api-sdk: ^1.2.1
  type-fest: ^4.41.0
  typescript: ^5.8.3
  vitest: ^3.2.4
  wikibase-sdk: ^10.2.3
  xsai: ^0.3.0-beta.4
  zod: ^3.25.67
  zod-validation-error: ^3.5.2
  zoominfo-api-auth-client: ^1.0.1

ignoredBuiltDependencies:
  - '@fisch0920/config'

updateConfig:
  ignoreDependencies:
    - p-throttle
    - '@nangohq/node'
